In [1]:
import pandas as pd
import numpy as np

In [2]:
data_nurbed=pd.read_csv(r"C:\Users\Edison New\Desktop\HWG Q1 Reporting 2025\Raw data sets from the app\Agric Nursery Bed seed distribution reports (household)#check4.csv")

In [3]:
data_nurbed.head()

,guid,region_name,district_name,cluster_name,village_name,cohort,cycle,reporter,reporter_email,name,...,total_quantity,variety,hours_to_complete,officials,other_officials,challenges,other_challenges,latitude,longitude,created_at
0,E107A042-7A8A-89A2-9187-8C1351DFF6D2,South West,Kitagwenda,Nyakacwamba,Nyakacwamba_2,2025,A,Charles,charles.tweteise@raisingthevillage.org,Tumukurate Ignitias,...,1,Amaranths,4,NaN,NaN,NaN,NaN,0.006664,30.368231,16/02/2025 18:57
1,6E1DDA09-2AF6-8D90-43DA-482AC1209B2A,South West,Kitagwenda,Nyakacwamba,Nyakacwamba_2,2025,A,Charles,charles.tweteise@raisingthevillage.org,Tumukurate Ignitias,...,1,Black night shade,4,NaN,NaN,NaN,NaN,0.006664,30.368231,16/02/2025 18:57
2,DFD6F1A5-E49B-004D-2C08-98065600308B,South West,Kitagwenda,Nyakacwamba,Nyakacwamba_2,2025,A,Charles,charles.tweteise@raisingthevillage.org,Tumukurate Ignitias,...,1,Cabbage,4,NaN,NaN,NaN,NaN,0.006664,30.368231,16/02/2025 18:57
3,D4BF349A-CA70-8DEF-7546-EF12DC3716DE,South West,Kitagwenda,Nyakacwamba,Nyakacwamba_2,2025,A,Charles,charles.tweteise@raisingthevillage.org,Tumukurate Ignitias,...,1,Green Pepper,4,NaN,NaN,NaN,NaN,0.006664,30.368231,16/02/2025 18:57
4,D4507CF4-76DB-4053-84AC-E76C44439EF5,South West,Kitagwenda,Nyakacwamba,Nyakacwamba_2,2025,A,Charles,charles.tweteise@raisingthevillage.org,Tumukurate Ignitias,...,1,Nakati,4,NaN,NaN,NaN,NaN,0.006664,30.368231,16/02/2025 18:57

In [4]:
census=pd.read_excel(r"C:\Users\Edison New\Desktop\HWG Q1 Reporting 2025\Raw data sets from the app\check2 hWG Q1 files\HWG Data request (1).xlsx")

In [5]:
data_nurbed.columns

Index(['guid', 'region_name', 'district_name', 'cluster_name', 'village_name',
       'cohort', 'cycle', 'reporter', 'reporter_email', 'name', 'household_id',
       'gender', 'age', 'contact', 'marital_status', 'total_quantity',
       'variety', 'hours_to_complete', 'officials', 'other_officials',
       'challenges', 'other_challenges', 'latitude', 'longitude',
       'created_at'],
      dtype='object')

In [6]:
census.columns

Index(['district', 'subcounty', 'parish_t', 'Cluster', 'village', 'Cycle',
       'Cohort', 'hhid'],
      dtype='object')

In [7]:
data_nurbed_clean=data_nurbed[data_nurbed['household_id'].isin(census['hhid'])]

In [8]:
data_nurbed_clean.shape

(394, 25)

In [9]:
data_nur=data_nurbed.pivot_table(index=['district_name','variety'],values=['total_quantity'],aggfunc="sum")
data_nur=data_nur.reset_index()

In [10]:
data_nur

   district_name               variety  total_quantity
0     Kitagwenda             Amaranths              26
1     Kitagwenda     Black night shade              27
2     Kitagwenda               Cabbage              27
3     Kitagwenda          Green Pepper              26
4     Kitagwenda                Nakati              26
5     Kitagwenda      Purple Eggplants              21
6     Kitagwenda               Spinach              27
7     Kitagwenda           Sukuma Wiki              26
8     Kitagwenda              Tomatoes              52
9     Kitagwenda       White Eggplants              26
10         Rakai  African spider Plant              13
11         Rakai             Amaranths              17
12         Rakai     Black night shade               3
13         Rakai               Cabbage              47
14         Rakai          Green Pepper              17
15         Rakai                Nakati              14
16         Rakai      Purple Eggplants              17
17         Rakai               Spinach              34
18         Rakai           Sukuma Wiki              17
19         Rakai       White Eggplants               7

In [11]:
data_design=pd.read_csv(r"C:\\Users\\Edison New\Desktop\\HWG Q1 Reporting 2025\\Raw data sets from the app\design nurserybed summary.csv")

In [12]:
data_design.columns

Index(['Unnamed: 0', 'Country ', 'district_name', 'work_streams', 'category',
       'cluster_name', 'village_name', 'cohort', 'cycle',
       'hot_pepper_tins_organic_pesticides', 'onions_bags_organic_pesticides',
       'Spinach', 'AFRICAN SPIDER PLANT', 'Amaranths', 'Tomatoes',
       'BLACK NIGHT SHADE', 'Purple Eggplants', 'Green Pepper',
       'White Eggplants', 'Cabbage', 'Nakati', 'Sukuma Wiki'],
      dtype='object')

In [13]:
data_design = data_design.melt(
       value_vars=['hot_pepper_tins_organic_pesticides', 'onions_bags_organic_pesticides', 'Spinach', 'AFRICAN SPIDER PLANT', 'Amaranths', 'Tomatoes', 'BLACK NIGHT SHADE', 'Purple Eggplants', 'Green Pepper', 'White Eggplants', 'Cabbage', 'Nakati', 'Sukuma Wiki'],
       value_name='total_quantity',
       var_name='variety',
       id_vars=['district_name', 'cohort', 'cycle']
)

In [14]:
data_design_pivot=data_design.pivot_table(index=['district_name','variety'],values=['total_quantity'],aggfunc="sum")

In [15]:
data_design_pivot = data_design_pivot.reset_index()

In [16]:
data_design_pivot['variety'] = data_design_pivot['variety'].str.strip()
data_design_pivot.head(25)

   district_name                             variety  total_quantity
0     Kitagwenda                AFRICAN SPIDER PLANT             0.0
1     Kitagwenda                           Amaranths            26.0
2     Kitagwenda                   BLACK NIGHT SHADE            27.0
3     Kitagwenda                             Cabbage            27.0
4     Kitagwenda                        Green Pepper            26.0
5     Kitagwenda                              Nakati            26.0
6     Kitagwenda                    Purple Eggplants            21.0
7     Kitagwenda                             Spinach            27.0
8     Kitagwenda                         Sukuma Wiki            26.0
9     Kitagwenda                            Tomatoes            52.0
10    Kitagwenda                     White Eggplants            26.0
11    Kitagwenda  hot_pepper_tins_organic_pesticides            22.6
12    Kitagwenda      onions_bags_organic_pesticides          2031.0
13         Rakai                AFRICAN SPIDER PLANT            13.0
14         Rakai                           Amaranths            17.0
15         Rakai                   BLACK NIGHT SHADE             3.0
16         Rakai                             Cabbage            47.0
17         Rakai                        Green Pepper            17.0
18         Rakai                              Nakati            14.0
19         Rakai                    Purple Eggplants            17.0
20         Rakai                             Spinach            34.0
21         Rakai                         Sukuma Wiki            17.0
22         Rakai                            Tomatoes             0.0
23         Rakai                     White Eggplants             7.0
24         Rakai  hot_pepper_tins_organic_pesticides            22.1

In [17]:
data_design_pivot['variety'].replace({'AFRICAN SPIDER PLANT':'African spider Plant',
                                  'BLACK NIGHT SHADE':'Black night shade'}, inplace=True)

C:\Users\Edison New\AppData\Local\Temp\ipykernel_18088\2557651172.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data_design_pivot['variety'].replace({'AFRICAN SPIDER PLANT':'African spider Plant',

In [18]:
data_design_pivot = data_design_pivot[~data_design_pivot['variety'].isin(['hot_pepper_tins_organic_pesticides', 'onions_bags_organic_pesticides'])]

In [19]:
data_design_pivot

   district_name               variety  total_quantity
0     Kitagwenda  African spider Plant             0.0
1     Kitagwenda             Amaranths            26.0
2     Kitagwenda     Black night shade            27.0
3     Kitagwenda               Cabbage            27.0
4     Kitagwenda          Green Pepper            26.0
5     Kitagwenda                Nakati            26.0
6     Kitagwenda      Purple Eggplants            21.0
7     Kitagwenda               Spinach            27.0
8     Kitagwenda           Sukuma Wiki            26.0
9     Kitagwenda              Tomatoes            52.0
10    Kitagwenda       White Eggplants            26.0
13         Rakai  African spider Plant            13.0
14         Rakai             Amaranths            17.0
15         Rakai     Black night shade             3.0
16         Rakai               Cabbage            47.0
17         Rakai          Green Pepper            17.0
18         Rakai                Nakati            14.0
19         Rakai      Purple Eggplants            17.0
20         Rakai               Spinach            34.0
21         Rakai           Sukuma Wiki            17.0
22         Rakai              Tomatoes             0.0
23         Rakai       White Eggplants             7.0

In [20]:
clean_data_nurserybed=data_design_pivot.merge(data_nur,on=['district_name','variety'],suffixes=('_design','_system'),how='outer')

In [24]:
filepath = 'C:\\Users\\Edison New\\Desktop\\HWG Q1 Reporting 2025\\Final outputs\\nurserybedfinal analysis.csv'
clean_data_nurserybed.to_csv(filepath, index=False)